### ISSUE TITLE
Resvg in next: using a function from multiple routes breaks the build

### ISSUE THREAD

**Issue by udatny** [eisberg-labs/nextjs-node-loader#45] opened 2024-08-20 10:24 UTC
**Describe the bug**
Once I reference a function using resvg more than once from a route, the next build fails.
Which version of Next.js? 14.2.5
Which version of nextjs-node-loader? 1.1.5

**To Reproduce**
Steps to reproduce the behavior or even better. Share me a link to repository with reproducable:

Dear [amarjanica](https://github.com/eisberg-labs/nextjs-node-loader/commits?author=amarjanica)
I am using your loader to work with resvg in next (14.x). I encountered an issue and isolated it as good as possible. I am stuck there and asking for your support.

-	I created a fork here and added another example where I can demonstrate the issue: https://github.com/udatny/nextjs-node-loader/tree/main/examples/next-14-resvg
-	resvg is a toolkit for rendering svgs to images. https://github.com/yisibl/resvg-js

The issue is, that once I reference the function using resvg more than once, the build fails. 
You can checkout my fork, go to the examples/next-14-resvg folder and reproduce the issue as follows:
-	in the next-14-resvg folder, do a `npm install`
-	followed by `npm run dev`
-	call the api endpoints: 
o	http://localhost:3000/api/render2d/sdfsfd
o	http://localhost:3000/api/renderXd/sdfsfd

all is good up to here. 

These two endpoints do actually exactly the same, just listen on a different path. Expectation is, that you get a 200
-	Now, if you run a npm run build, you will encounter the issue I am talking about. In my case, I am on windows, in a git bash, I get a
`Error: Cannot find module './resvgjs.win32-x64-msvc.node'`

```
> Build error occurred
Error: Failed to collect page data for /api/render2d/[slug]
```

randomly for one of the the api endpoints. 

-	To resolve the issue, you can just delete one of the identical api folders (for example “/app/api/renderXd”) and the build will pass afterwards
-	To reestablish the build issue, just copy the remaining api folder and give it another name, the build will fail again. 

Since you seem to be familiar with webpack and loading and building I’d be happy if you could have a look into that. 
Thanks.

**Comment by amarjanica** [comment] 2024-08-22 09:21
Hey @udatny, thank you for detailed reporting of this issue! I really appreciate your contribution. Unfortunately, I’m a bit swamped at the moment, but I’ll try to make some time in the next few days to look into this. I’ll keep you updated on the progress.

**Comment by aluferraz** [comment] 2024-08-29 13:54
+1, same issue here

**Comment by amarjanica** [comment] 2024-08-30 13:48
Hey @udatny sorry for being late. Good thing is that I have the correct environment to reproduce this issue as I've formatted my Ubuntu to Windows. There's a couple of issues and I'm not sure it's all due to nextjs-node-loader.
1. Loader wasn't called at all - I ran the build in debug mode, put a breakpoint and it wasn't until I changed the 
```
 config.module.rules.push({
      test: /.+.node$/ig,
      use: [
        {
          loader: 'nextjs-node-loader',
          options: {
            flags: os.constants.dlopen.RTLD_NOW,
            outputPath: config.output.path
          },
        },
      ],
    });
``` 
it started to call my loader. I'm not sure why the original regex doesn't work in this case.

2. When build process started, correct loader gets called but I get all of these different platforms:
Is it something you need to configure in your native build configuration?
It requests all possible platforms.
In my case it should only require resvgjs.win32-x64-msvc.node which is in the .next/server/app/chunks:

```
./node_modules/@resvg/resvg-js/js-binding.js
Module not found: Can't resolve './resvgjs.android-arm64.node' in '...\nextjs-node-loader2\examples\next-14-resvg\node_modules\@resvg\resvg-js'
@resvg/resvg-js-android-arm-eabi
```

**Comment by amarjanica** [comment] 2024-10-11 13:50
This might be related to #48, I'm closing this issue, try the 1.1.8

**Closed by amarjanica** 2024-10-11 13:50 UTC

**Comment by udatny** [comment] 2024-10-15 12:08
thank you very much for taking care of my issue. i tried once with the modified test regex as you proposed: test: /.+.node$/ig,
the results were mixed. while it worked on windows, the build failed on linux. 

so i searched further and got this hint here: https://github.com/yisibl/resvg-js/issues/315#issuecomment-2395408012

and by using this, i dont need any custom loader anymore and it works in all situations (e.g win/linux dev / build).
